version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cobuilders-postgres
    environment:
      POSTGRES_DB: cobuilders_dev
      POSTGRES_USER: cobuilders
      POSTGRES_PASSWORD: cobuilders123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - cobuilders-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cobuilders -d cobuilders_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cobuilders-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cobuilders-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: cobuilders-adminer
    ports:
      - "8080:8080"
    networks:
      - cobuilders-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  cobuilders-network:
    driver: bridge
