import type { Metadata, Viewport } from "next";
import { Analytics } from "@vercel/analytics/next";
import { TooltipProvider } from "@/components/ui/tooltip";
import { BottomNav } from "@/components/bottom-nav";
import { AuthProvider } from "@/components/auth-provider";
import { MaahiChat } from "@/components/maahi-chat";
import { ProfileLauncher } from "@/components/profile-launcher";
import { PushSubscriber } from "@/components/push-subscriber";
import { ThemeProvider } from "@/components/theme-provider";
import { AnalyticsScripts } from "@/components/analytics-scripts";
import { ConsentBanner } from "@/components/consent-banner";
import {
  organizationSchema,
  softwareApplicationSchema,
  websiteSchema,
  jsonLdString,
} from "@/lib/structured-data";
import "./globals.css";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") || "https://biggdate.app";
const APP_TITLE = "BiggDate — AI Dating App for Intentional Adults";
const APP_DESCRIPTION =
  "BiggDate is the AI-led dating app that finds the one who's been waiting for you. Curated daily matches built around a psychological Soul Profile, not swipes.";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: APP_TITLE,
  description: APP_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "BiggDate",
  },
  openGraph: {
    type: "website",
    siteName: "BiggDate",
    title: APP_TITLE,
    description: APP_DESCRIPTION,
    url: APP_URL,
    // og:image is generated by src/app/opengraph-image.tsx (file convention).
    // Keep the OG locale neutral — the phone picker is global and a regional
    // tag here biases social previews + Apple/Google indexing.
    locale: "en",
  },
  twitter: {
    card: "summary_large_image",
    title: APP_TITLE,
    description: APP_DESCRIPTION,
    // twitter:image is generated by src/app/twitter-image.tsx.
  },
  alternates: {
    canonical: APP_URL,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // WCAG 1.4.4: never block zoom. Mobile Safari respects user pinch even
  // when we set initialScale, so the only thing maximumScale/userScalable=false
  // bought us was an accessibility violation.
  maximumScale: 5,
  userScalable: true,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f7f8ff" },
    { media: "(prefers-color-scheme: dark)", color: "#050914" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ position: "relative" }} suppressHydrationWarning>
      <head>
        {/* JSON-LD: Organization, SoftwareApplication, WebSite — for AEO/GEO discovery */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdString(organizationSchema()) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdString(softwareApplicationSchema()) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdString(websiteSchema()) }}
        />
        {/*
          Third-party trackers (GTM/GA4, Meta Pixel, Microsoft Clarity) load
          ONLY after the user accepts in <ConsentBanner /> — see
          src/components/analytics-scripts.tsx. Keeps us compliant with EU
          GDPR/ePrivacy and India DPDP 2023 by default. Vercel Analytics is
          first-party + cookieless and mounts unconditionally below.
        */}
      </head>
      <body
        className="antialiased bg-[var(--bd-bg)] text-[var(--bd-text)] min-h-screen pb-nav"
        style={{ position: "relative" }}
      >
        {/*
          GTM/Meta Pixel <noscript> fallbacks intentionally removed alongside
          the JS tags. Loading them unconditionally would defeat the consent
          gate (they're tracking pixels too, just without JS).
        */}
        {/* Skip-to-content link for keyboard / screen-reader users (WCAG 2.4.1). */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-md focus:bg-[var(--bd-text)] focus:px-4 focus:py-2 focus:text-[var(--bd-bg)] focus:shadow-lg"
        >
          Skip to main content
        </a>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <AuthProvider>
              <div id="main-content" tabIndex={-1}>
                {children}
              </div>
              <PushSubscriber />
              <ProfileLauncher />
              <BottomNav />
              <MaahiChat />
              <ConsentBanner />
            </AuthProvider>
          </TooltipProvider>
          <AnalyticsScripts />
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
