/**
 * Seed 14 dummy profiles for dev/demo use.
 *
 * Usage:
 *   npm run seed
 *   # or directly:
 *   npx tsx --env-file=.env.local scripts/seed-profiles.ts
 *
 * Pass --reset to wipe existing seed rows before inserting.
 */

import { sql } from "../src/lib/db";
import { upsertAccountHandle, upsertProfile } from "../src/lib/repo";
import type { Profile } from "../src/lib/types";

// Deterministic UUIDs: 00000000-0000-0000-0000-0000000000XX
function seedId(n: number) {
  return `00000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
}

interface Persona {
  userId: string;
  email: string;
  username: string;
  fullName: string;
  profile: Omit<Profile, "photos"> & { photos: string[] };
}

const PERSONAS: Persona[] = [
  // ── 01 Arjun Mehta · Bangalore · M · 28 · Secure · Serious ────────────────
  {
    userId: seedId(1),
    email: "arjun.mehta@seed.biggdate.app",
    username: "arjun_mehta",
    fullName: "Arjun Mehta",
    profile: {
      name: "Arjun Mehta",
      age: 28,
      birthday: "1997-07-15",
      zodiac: "Cancer",
      city: "Bangalore",
      gender: "Man",
      orientation: "Straight",
      pronouns: "he/him",
      hometown: "Jaipur",
      jobTitle: "Software Engineer",
      company: "Thoughtworks",
      education: "IIT Delhi",
      height: "5'11\"",
      religion: "Hindu",
      politics: "Liberal",
      ethnicity: "Indian",
      partnerGender: "Woman",
      intent: "serious",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "yes",
      loveLanguage: "Quality Time",
      drinking: "social",
      smoking: "never",
      exercise: "often",
      languages: ["Hindi", "English", "Kannada"],
      interests: ["hiking", "jazz", "cooking", "open-source", "philosophy"],
      pets: ["dog"],
      dealbreakers: ["dishonesty", "no ambition"],
      partnerAgeMin: 24,
      partnerAgeMax: 33,
      attachment: "Secure",
      attachmentScore: 82,
      readinessScore: 82,
      growthAreas: ["vulnerability", "asking for help"],
      strengths: ["emotional availability", "consistency", "deep listening"],
      coreValues: ["integrity", "growth", "family", "curiosity"],
      summary:
        "Arjun is a grounded, emotionally available engineer who leads with calm. He left Jaipur for Bangalore to build things that matter — and applies the same intentionality to relationships. He's not in a rush, but he knows what he wants.",
      coachingFocus: "Learning to voice needs without over-explaining them.",
      photos: [],
      prompts: [
        { question: "The way to my heart is", answer: "A long walk with nowhere to be and a really good question." },
        { question: "I'm looking for", answer: "Someone who finds comfort in the ordinary." },
        { question: "My love language is", answer: "Showing up — even when it's inconvenient." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "Direct but calm. I name the issue early so it doesn't fester.",
      familyExpectations: "Close-knit. I visit home once a month and my partner would feel welcomed there.",
      lifeArchitecture: "Bangalore for now, maybe Bombay in 5 years. Open to building a life outside metros eventually.",
      offers: ["emotional steadiness", "adventure planning", "home-cooked Sunday meals"],
      needs: ["intellectual spark", "someone who matches my pace", "honesty over comfort"],
    },
  },

  // ── 02 Nikhil Rao · Bangalore · M · 23 · Anxious · Exploring ──────────────
  {
    userId: seedId(2),
    email: "nikhil.rao@seed.biggdate.app",
    username: "nikhil_rao",
    fullName: "Nikhil Rao",
    profile: {
      name: "Nikhil Rao",
      age: 23,
      birthday: "2002-11-03",
      zodiac: "Scorpio",
      city: "Bangalore",
      gender: "Man",
      orientation: "Straight",
      pronouns: "he/him",
      hometown: "Mysuru",
      jobTitle: "UX Designer",
      company: "Razorpay",
      education: "NID Ahmedabad",
      height: "5'9\"",
      religion: "Agnostic",
      politics: "Progressive",
      ethnicity: "Indian",
      partnerGender: "Woman",
      intent: "exploring",
      relationshipStyle: "Figuring it out",
      hasKids: false,
      wantsKids: "open",
      loveLanguage: "Words of Affirmation",
      drinking: "social",
      smoking: "social",
      exercise: "sometimes",
      languages: ["Kannada", "English", "Hindi"],
      interests: ["typography", "indie music", "film photography", "board games", "cycling"],
      pets: [],
      dealbreakers: ["cruelty", "no sense of humour"],
      partnerAgeMin: 21,
      partnerAgeMax: 28,
      attachment: "Anxious",
      attachmentScore: 45,
      readinessScore: 45,
      growthAreas: ["self-soothing", "not over-texting", "tolerating uncertainty"],
      strengths: ["creativity", "attentiveness", "making people feel seen"],
      coreValues: ["authenticity", "creativity", "connection"],
      summary:
        "Nikhil is a 23-year-old designer who's just starting to figure out who he is outside of work. He's curious, a little intense, and gives a lot in relationships — sometimes more than he should. He's here to understand himself as much as to meet someone.",
      coachingFocus: "Building a secure base so he doesn't seek constant reassurance.",
      photos: [],
      prompts: [
        { question: "A random fact I love", answer: "The font used in the Mumbai local train signs hasn't changed since 1956." },
        { question: "I'm weirdly competitive about", answer: "Wordle. I will not elaborate." },
        { question: "I'll know it's right if", answer: "Silences don't feel awkward." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I tend to go quiet first, then want to talk it through properly once I've processed.",
      familyExpectations: "Close to my parents but still finding my independence. It's a work in progress.",
      lifeArchitecture: "Bangalore for 2-3 years, then maybe freelancing from wherever feels right.",
      offers: ["genuine attention", "creative problem-solving", "remembering the small things you mention"],
      needs: ["patience", "reassurance during uncertain times", "someone who initiates too"],
    },
  },

  // ── 03 Ananya Bose · Bangalore · F · 30 · Anxious · Serious ──────────────
  {
    userId: seedId(3),
    email: "ananya.bose@seed.biggdate.app",
    username: "ananya_bose",
    fullName: "Ananya Bose",
    profile: {
      name: "Ananya Bose",
      age: 30,
      birthday: "1995-03-22",
      zodiac: "Aries",
      city: "Bangalore",
      gender: "Woman",
      orientation: "Straight",
      pronouns: "she/her",
      hometown: "Kolkata",
      jobTitle: "Data Scientist",
      company: "Flipkart",
      education: "IISc Bangalore",
      height: "5'5\"",
      religion: "Hindu",
      politics: "Moderate",
      ethnicity: "Indian",
      partnerGender: "Man",
      intent: "serious",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "yes",
      loveLanguage: "Acts of Service",
      drinking: "social",
      smoking: "never",
      exercise: "sometimes",
      languages: ["Bengali", "English", "Hindi"],
      interests: ["Rabindranath Tagore", "data viz", "pottery", "solo travel", "street food"],
      pets: ["cat"],
      dealbreakers: ["emotional unavailability", "dismissiveness"],
      partnerAgeMin: 28,
      partnerAgeMax: 38,
      attachment: "Anxious",
      attachmentScore: 58,
      readinessScore: 68,
      growthAreas: ["trusting without proof", "letting relationships unfold slowly"],
      strengths: ["perceptiveness", "loyalty", "depth of feeling"],
      coreValues: ["family", "intellectual honesty", "warmth", "perseverance"],
      summary:
        "Ananya moved from Kolkata to Bangalore at 22 and has built a life she's proud of — but the one thing she hasn't cracked is finding someone who matches her emotional depth. She over-analyses, she knows it, and she's working on it.",
      coachingFocus: "Learning to distinguish real red flags from anxiety noise.",
      photos: [],
      prompts: [
        { question: "I'm the kind of person who", answer: "Will send you a 3-minute voice note at 11pm about something that reminded me of a conversation we had 6 months ago." },
        { question: "Kolkata taught me", answer: "That taking your time over a meal is a form of respect." },
        { question: "I want someone who", answer: "Argues with me about books and then holds my hand." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I bring things up quickly — probably too quickly sometimes. I'm learning to let things breathe.",
      familyExpectations: "Very important. I'll always be close to my parents. Partner needs to understand that.",
      lifeArchitecture: "Bangalore long-term. I'd consider Kolkata later in life to be near family.",
      offers: ["fierce loyalty", "home-cooked Bengali food", "someone who will actually remember what you said"],
      needs: ["consistency", "follow-through", "emotional reciprocity"],
    },
  },

  // ── 04 Rohan Sharma · Delhi · M · 35 · Anxious · Marriage ─────────────────
  {
    userId: seedId(4),
    email: "rohan.sharma@seed.biggdate.app",
    username: "rohan_sharma",
    fullName: "Rohan Sharma",
    profile: {
      name: "Rohan Sharma",
      age: 35,
      birthday: "1990-08-09",
      zodiac: "Leo",
      city: "Delhi",
      gender: "Man",
      orientation: "Straight",
      pronouns: "he/him",
      hometown: "Chandigarh",
      jobTitle: "Management Consultant",
      company: "McKinsey & Company",
      education: "IIM Ahmedabad",
      height: "6'0\"",
      religion: "Hindu",
      politics: "Centrist",
      ethnicity: "Indian",
      partnerGender: "Woman",
      intent: "marriage",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "yes",
      loveLanguage: "Quality Time",
      drinking: "social",
      smoking: "never",
      exercise: "often",
      languages: ["Hindi", "English", "Punjabi"],
      interests: ["squash", "long-form journalism", "whisky tasting", "economic history", "mentoring"],
      pets: [],
      dealbreakers: ["lack of ambition", "family estrangement"],
      partnerAgeMin: 27,
      partnerAgeMax: 35,
      attachment: "Anxious",
      attachmentScore: 62,
      readinessScore: 74,
      growthAreas: ["being present outside of work mode", "not measuring everything"],
      strengths: ["drive", "generosity", "reliability under pressure"],
      coreValues: ["achievement", "family", "loyalty", "service"],
      summary:
        "Rohan has spent his 30s building a career he's proud of — and slowly realising it doesn't fill the room the way a relationship would. He's ready for something real, comes with baggage like everyone else, and is trying to be honest about it.",
      coachingFocus: "Reconnecting with emotional needs he's sidelined for career.",
      photos: [],
      prompts: [
        { question: "My ideal Sunday", answer: "Farmers market, a long lunch, the Sunday NYT, no phone notifications." },
        { question: "I'm working on", answer: "Being someone whose presence people actually feel." },
        { question: "You should know that", answer: "I take time to warm up but once I'm in, I'm fully in." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I tend to intellectualise conflict. Working on sitting in the discomfort instead of solving it.",
      familyExpectations: "Traditional in values, modern in execution. I want a partner, not a project.",
      lifeArchitecture: "Delhi for the next 5 years. Open to relocation if the right opportunity and right person align.",
      offers: ["financial security", "structured vision for the future", "deep loyalty once committed"],
      needs: ["emotional warmth", "someone who calls me out", "a life outside the office"],
    },
  },

  // ── 05 Aditya Verma · Delhi · M · 31 · Avoidant · Casual ─────────────────
  {
    userId: seedId(5),
    email: "aditya.verma@seed.biggdate.app",
    username: "aditya_verma",
    fullName: "Aditya Verma",
    profile: {
      name: "Aditya Verma",
      age: 31,
      birthday: "1994-12-17",
      zodiac: "Sagittarius",
      city: "Delhi",
      gender: "Man",
      orientation: "Straight",
      pronouns: "he/him",
      hometown: "Lucknow",
      jobTitle: "Lawyer",
      company: "AZB & Partners",
      education: "NLSIU Bangalore",
      height: "5'10\"",
      religion: "Agnostic",
      politics: "Liberal",
      ethnicity: "Indian",
      partnerGender: "Woman",
      intent: "casual",
      relationshipStyle: "Non-exclusive for now",
      hasKids: false,
      wantsKids: "open",
      loveLanguage: "Physical Touch",
      drinking: "regularly",
      smoking: "social",
      exercise: "sometimes",
      languages: ["Hindi", "English", "Urdu"],
      interests: ["Urdu poetry", "motorcycles", "live comedy", "geopolitics", "midnight drives"],
      pets: [],
      dealbreakers: ["clinginess", "no intellectual curiosity"],
      partnerAgeMin: 24,
      partnerAgeMax: 32,
      attachment: "Avoidant",
      attachmentScore: 35,
      readinessScore: 40,
      growthAreas: ["staying present", "not disappearing when things get real"],
      strengths: ["wit", "independence", "intensity in the moment"],
      coreValues: ["freedom", "honesty", "intellectual depth"],
      summary:
        "Aditya is charming, self-aware, and chronically non-committal. He'll tell you that upfront. He's had one serious relationship that ended because he couldn't let her in — and he's still processing what that says about him.",
      coachingFocus: "Understanding his avoidance patterns before they cost him another good thing.",
      photos: [],
      prompts: [
        { question: "I'm honest about the fact that", answer: "I'm better at beginnings than middles." },
        { question: "Ghalib said it best", answer: "\"Hazaron khwahishein aisi\" — yeah, that's me." },
        { question: "What I'm not looking for", answer: "Labels. What I am looking for: good conversation and real chemistry." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: false,
      showEducation: true,
      conflictStyle: "I withdraw. I know it. I'm trying to catch myself before I do it.",
      familyExpectations: "Cordial but distant. Family is not the centre of my life and I won't pretend otherwise.",
      lifeArchitecture: "Delhi indefinitely. I like the chaos.",
      offers: ["sharp conversation", "zero pretence", "the kind of attention that makes you feel like the only person in the room"],
      needs: ["space without it meaning something", "someone secure enough to not need constant reassurance"],
    },
  },

  // ── 06 Shreya Reddy · Delhi · F · 33 · Avoidant · Exploring ──────────────
  {
    userId: seedId(6),
    email: "shreya.reddy@seed.biggdate.app",
    username: "shreya_reddy",
    fullName: "Shreya Reddy",
    profile: {
      name: "Shreya Reddy",
      age: 33,
      birthday: "1992-05-28",
      zodiac: "Gemini",
      city: "Delhi",
      gender: "Woman",
      orientation: "Straight",
      pronouns: "she/her",
      hometown: "Hyderabad",
      jobTitle: "Journalist",
      company: "The Wire",
      education: "ACJ Chennai",
      height: "5'6\"",
      religion: "Agnostic",
      politics: "Left-leaning",
      ethnicity: "Indian",
      partnerGender: "Man",
      intent: "exploring",
      relationshipStyle: "Open to anything honest",
      hasKids: false,
      wantsKids: "open",
      loveLanguage: "Words of Affirmation",
      drinking: "social",
      smoking: "social",
      exercise: "sometimes",
      languages: ["Telugu", "English", "Hindi"],
      interests: ["investigative journalism", "cinema", "Carnatic music", "feminism", "bookshops"],
      pets: ["cat"],
      dealbreakers: ["fragile ego", "no politics"],
      partnerAgeMin: 29,
      partnerAgeMax: 40,
      attachment: "Avoidant",
      attachmentScore: 40,
      readinessScore: 45,
      growthAreas: ["letting someone in past the interesting-surface level", "accepting care without suspicion"],
      strengths: ["independence", "moral clarity", "turning difficult truths into stories"],
      coreValues: ["justice", "truth", "freedom", "curiosity"],
      summary:
        "Shreya covers political stories for a living and has learned to hold her cards close. She's funny, fiercely opinionated, and has kept every relationship at arm's length. She's starting to wonder if that's protection or just habit.",
      coachingFocus: "Learning the difference between privacy and emotional walls.",
      photos: [],
      prompts: [
        { question: "Don't date me if", answer: "You need someone who'll always be reachable. I go dark when I'm on a story." },
        { question: "I'll probably ask you", answer: "What you actually believe, not what's safe to say." },
        { question: "My tell is", answer: "I laugh loudest at things that make me uncomfortable." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I argue to understand, not to win. But I argue.",
      familyExpectations: "Complicated. I love my family and disagree with most of their values. My partner needs to hold that complexity.",
      lifeArchitecture: "Delhi for work. Would consider Hyderabad if I ever slow down.",
      offers: ["radical honesty", "never boring", "a partner who is genuinely witnessed"],
      needs: ["someone not threatened by my work", "space without drama", "intellectual equals only"],
    },
  },

  // ── 07 Priya Kapoor · Mumbai · F · 22 · Secure · Serious ─────────────────
  {
    userId: seedId(7),
    email: "priya.kapoor@seed.biggdate.app",
    username: "priya_kapoor",
    fullName: "Priya Kapoor",
    profile: {
      name: "Priya Kapoor",
      age: 22,
      birthday: "2003-09-14",
      zodiac: "Virgo",
      city: "Mumbai",
      gender: "Woman",
      orientation: "Straight",
      pronouns: "she/her",
      hometown: "Mumbai",
      jobTitle: "Marketing Lead",
      company: "boAt",
      education: "Narsee Monjee College",
      height: "5'4\"",
      religion: "Hindu",
      politics: "Progressive",
      ethnicity: "Indian",
      partnerGender: "Man",
      intent: "serious",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "yes",
      loveLanguage: "Quality Time",
      drinking: "social",
      smoking: "never",
      exercise: "often",
      languages: ["Hindi", "English", "Marathi"],
      interests: ["branding", "Bollywood", "pilates", "thrifting", "dalgona coffee at 1am"],
      pets: [],
      dealbreakers: ["no ambition", "bad hygiene"],
      partnerAgeMin: 22,
      partnerAgeMax: 30,
      attachment: "Secure",
      attachmentScore: 75,
      readinessScore: 60,
      growthAreas: ["not rushing emotional timelines", "distinguishing serious from safe"],
      strengths: ["social warmth", "energy", "knowing what she wants"],
      coreValues: ["ambition", "fun", "family", "loyalty"],
      summary:
        "Priya grew up in Mumbai and never left — she doesn't need to. She's built a career most 22-year-olds would envy and still makes it to Sunday lunch at her parents' place every week. She wants someone who hustles and laughs in equal measure.",
      coachingFocus: "Not settling for comfortable when she deserves exciting.",
      photos: [],
      prompts: [
        { question: "My love language in practice", answer: "Sending you a reel at 2am that made me think of you." },
        { question: "I will always have an opinion about", answer: "Movie soundtracks. Always." },
        { question: "Non-negotiables", answer: "Ambition, kindness, and someone who can keep up with my mother's interrogation." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I say what's bothering me right away. I can't do the cold war thing.",
      familyExpectations: "Family is everything. Sundays are sacred. If you can't do family, we won't work.",
      lifeArchitecture: "Mumbai forever. Born here, building here.",
      offers: ["unmatched energy", "a full social life", "someone who'll hype you up in every room"],
      needs: ["emotional maturity", "someone grounded", "to be chosen consistently"],
    },
  },

  // ── 08 Vikram Nair · Mumbai · M · 26 · Avoidant · Exploring ──────────────
  {
    userId: seedId(8),
    email: "vikram.nair@seed.biggdate.app",
    username: "vikram_nair",
    fullName: "Vikram Nair",
    profile: {
      name: "Vikram Nair",
      age: 26,
      birthday: "1999-01-30",
      zodiac: "Aquarius",
      city: "Mumbai",
      gender: "Man",
      orientation: "Straight",
      pronouns: "he/him",
      hometown: "Kochi",
      jobTitle: "Founder",
      company: "Zeptago (stealth)",
      education: "BITS Pilani",
      height: "5'11\"",
      religion: "Agnostic",
      politics: "Libertarian",
      ethnicity: "Indian",
      partnerGender: "Woman",
      intent: "exploring",
      relationshipStyle: "Not sure yet",
      hasKids: false,
      wantsKids: "open",
      loveLanguage: "Acts of Service",
      drinking: "social",
      smoking: "never",
      exercise: "often",
      languages: ["Malayalam", "English", "Hindi"],
      interests: ["building things", "first-principles thinking", "cold water swimming", "chess", "Keralan food"],
      pets: [],
      dealbreakers: ["neediness", "no curiosity"],
      partnerAgeMin: 22,
      partnerAgeMax: 30,
      attachment: "Avoidant",
      attachmentScore: 32,
      readinessScore: 38,
      growthAreas: ["not treating relationships like optimization problems", "asking for what he needs"],
      strengths: ["vision", "independence", "solving hard problems"],
      coreValues: ["autonomy", "impact", "learning", "honesty"],
      summary:
        "Vikram is building his second startup at 26 and hasn't slept properly in two years. He's used to being the one who's all-in on the work and half-in on everything else. He knows this, finds it hard to change, but is starting to want to.",
      coachingFocus: "Recognising that intimacy isn't a distraction from his goals.",
      photos: [],
      prompts: [
        { question: "I'm most alive when", answer: "Something I built is being used by strangers." },
        { question: "I'll clear my schedule for", answer: "A 3am drive to Worli sea face if the conversation is good enough." },
        { question: "Honest warning", answer: "My phone is always on. That's both a feature and a bug." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I go problem-solving mode in conflict. I know that's not always what's needed.",
      familyExpectations: "I love my family in Kochi but I've built a separate life. Video calls, festivals, that's about it for now.",
      lifeArchitecture: "Mumbai for the startup. Wherever after exit.",
      offers: ["undivided attention when I'm present", "building a life that surprises you", "zero games"],
      needs: ["independence respected", "someone ambitious in their own right", "patience with the startup phase"],
    },
  },

  // ── 09 Tanvi Desai · Mumbai · F · 36 · Secure · Serious ──────────────────
  {
    userId: seedId(9),
    email: "tanvi.desai@seed.biggdate.app",
    username: "tanvi_desai",
    fullName: "Tanvi Desai",
    profile: {
      name: "Tanvi Desai",
      age: 36,
      birthday: "1989-06-11",
      zodiac: "Gemini",
      city: "Mumbai",
      gender: "Woman",
      orientation: "Straight",
      pronouns: "she/her",
      hometown: "Surat",
      jobTitle: "VP Finance",
      company: "HDFC Asset Management",
      education: "LSE London",
      height: "5'6\"",
      religion: "Hindu",
      politics: "Centrist",
      ethnicity: "Indian",
      partnerGender: "Man",
      intent: "serious",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "yes",
      loveLanguage: "Acts of Service",
      drinking: "social",
      smoking: "never",
      exercise: "often",
      languages: ["Gujarati", "English", "Hindi"],
      interests: ["macroeconomics", "contemporary art", "running", "wine", "Surat street food"],
      pets: [],
      dealbreakers: ["financial irresponsibility", "lack of self-awareness"],
      partnerAgeMin: 32,
      partnerAgeMax: 44,
      attachment: "Secure",
      attachmentScore: 80,
      readinessScore: 77,
      growthAreas: ["asking for emotional support without framing it as a problem to solve", "softening"],
      strengths: ["clarity", "follow-through", "making people feel safe"],
      coreValues: ["integrity", "security", "growth", "presence"],
      summary:
        "Tanvi spent her 20s in London building a career and returned to Mumbai at 32 to be closer to home. She's done with situationships and the 'let's see where it goes' era. She's ready for something intentional, and she brings the same energy she gives her work.",
      coachingFocus: "Allowing herself to be taken care of, not just relied on.",
      photos: [],
      prompts: [
        { question: "My version of romance is", answer: "Remembering how you take your chai and having it ready." },
        { question: "What I've unlearned", answer: "That being low-maintenance is a virtue." },
        { question: "I'm looking for", answer: "A partner, not a project. Someone who has their own gravity." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "Direct and calm. I don't escalate. I expect the same.",
      familyExpectations: "I want to build my own family. My parents are in Surat — we'll be close, not enmeshed.",
      lifeArchitecture: "Mumbai is home. I've stopped romanticising elsewhere.",
      offers: ["stability", "intellectual depth", "someone who shows up so consistently it stops being remarkable"],
      needs: ["emotional maturity", "ambition that isn't about ego", "someone ready for the same stage of life"],
    },
  },

  // ── 10 Kabir Patel · Ahmedabad · M · 34 · Secure · Marriage ──────────────
  {
    userId: seedId(10),
    email: "kabir.patel@seed.biggdate.app",
    username: "kabir_patel",
    fullName: "Kabir Patel",
    profile: {
      name: "Kabir Patel",
      age: 34,
      birthday: "1991-10-05",
      zodiac: "Libra",
      city: "Ahmedabad",
      gender: "Man",
      orientation: "Straight",
      pronouns: "he/him",
      hometown: "Vadodara",
      jobTitle: "Architect",
      company: "Studio Lotus",
      education: "CEPT University",
      height: "5'10\"",
      religion: "Hindu",
      politics: "Moderate",
      ethnicity: "Indian",
      partnerGender: "Woman",
      intent: "marriage",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "yes",
      loveLanguage: "Quality Time",
      drinking: "social",
      smoking: "never",
      exercise: "often",
      languages: ["Gujarati", "Hindi", "English"],
      interests: ["heritage architecture", "classical music", "pottery", "long cycling routes", "cooking"],
      pets: ["dog"],
      dealbreakers: ["dishonesty", "unkindness to strangers"],
      partnerAgeMin: 27,
      partnerAgeMax: 36,
      attachment: "Secure",
      attachmentScore: 85,
      readinessScore: 88,
      growthAreas: ["being clearer about his timeline", "not absorbing others' anxiety"],
      strengths: ["patience", "groundedness", "making space for others"],
      coreValues: ["beauty", "craft", "family", "community"],
      summary:
        "Kabir designs spaces for other people's lives and has quietly been building the foundation for his own. He's not flashy, he's not in a rush — but he knows exactly who he is and what he's building toward. He wants a partner who wants to build with him.",
      coachingFocus: "Moving from readiness into action — he's been 'almost there' for two years.",
      photos: [],
      prompts: [
        { question: "I'll show you Ahmedabad properly", answer: "Pols at 6am, Manek Chowk at midnight. That's the city." },
        { question: "I believe that", answer: "The way someone treats their home tells you everything about them." },
        { question: "I'm looking for", answer: "Someone to sit across from at dinner for the next fifty years." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I try to understand before I respond. I go slow in conflict but I don't go quiet.",
      familyExpectations: "Family is the architecture of everything. I want to build one.",
      lifeArchitecture: "Ahmedabad. I've chosen this city deliberately and I'm not leaving.",
      offers: ["a home that feels intentional", "steadiness", "someone who will be deeply known"],
      needs: ["emotional presence", "someone who wants the same future", "warmth in the everyday"],
    },
  },

  // ── 11 Kavya Shah · Ahmedabad · F · 24 · Fearful-Avoidant · Marriage ──────
  {
    userId: seedId(11),
    email: "kavya.shah@seed.biggdate.app",
    username: "kavya_shah",
    fullName: "Kavya Shah",
    profile: {
      name: "Kavya Shah",
      age: 24,
      birthday: "2001-02-18",
      zodiac: "Aquarius",
      city: "Ahmedabad",
      gender: "Woman",
      orientation: "Straight",
      pronouns: "she/her",
      hometown: "Ahmedabad",
      jobTitle: "Medical Resident",
      company: "Civil Hospital Ahmedabad",
      education: "B.J. Medical College",
      height: "5'3\"",
      religion: "Hindu",
      politics: "Apolitical",
      ethnicity: "Indian",
      partnerGender: "Man",
      intent: "marriage",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "yes",
      loveLanguage: "Quality Time",
      drinking: "never",
      smoking: "never",
      exercise: "sometimes",
      languages: ["Gujarati", "Hindi", "English"],
      interests: ["pediatrics", "classical dance (Bharatanatyam)", "Rumi", "afternoon naps", "Gujarati snacks"],
      pets: [],
      dealbreakers: ["disrespecting women", "no emotional intelligence"],
      partnerAgeMin: 24,
      partnerAgeMax: 34,
      attachment: "Fearful-Avoidant",
      attachmentScore: 42,
      readinessScore: 52,
      growthAreas: ["believing she deserves what she says she wants", "not pre-empting abandonment"],
      strengths: ["compassion", "service", "resilience"],
      coreValues: ["service", "family", "faith", "gentleness"],
      summary:
        "Kavya is a resident doctor who spends 14-hour shifts caring for others and is only starting to learn how to let someone care for her. She wants marriage but gets frightened by real closeness — she's aware of the contradiction and talking about it in therapy.",
      coachingFocus: "Breaking the push-pull pattern before it becomes her default.",
      photos: [],
      prompts: [
        { question: "I'm at my best when", answer: "I'm in the hospital. I'm still figuring out who I am everywhere else." },
        { question: "Something I want more of", answer: "Sunday mornings with nowhere to be." },
        { question: "I'll always make time for", answer: "Garba. It's the one place I feel completely free." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I freeze or fawn. I'm learning to speak up. Please be patient.",
      familyExpectations: "Very traditional. Family will always be central. I need a partner who fits into that warmly.",
      lifeArchitecture: "Ahmedabad for residency, then wherever my specialisation takes me.",
      offers: ["deep care", "someone who will love your family like her own", "patience built through medicine"],
      needs: ["gentleness", "consistency", "someone who stays when I get scared and push away"],
    },
  },

  // ── 12 Dev Iyer · Pune · M · 29 · Fearful-Avoidant · Serious ────────────
  {
    userId: seedId(12),
    email: "dev.iyer@seed.biggdate.app",
    username: "dev_iyer",
    fullName: "Dev Iyer",
    profile: {
      name: "Dev Iyer",
      age: 29,
      birthday: "1996-04-07",
      zodiac: "Aries",
      city: "Pune",
      gender: "Man",
      orientation: "Straight",
      pronouns: "he/him",
      hometown: "Chennai",
      jobTitle: "Product Manager",
      company: "Cred",
      education: "IIT Madras",
      height: "5'9\"",
      religion: "Agnostic",
      politics: "Liberal",
      ethnicity: "Indian",
      partnerGender: "Woman",
      intent: "serious",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "open",
      loveLanguage: "Words of Affirmation",
      drinking: "social",
      smoking: "never",
      exercise: "sometimes",
      languages: ["Tamil", "English", "Hindi"],
      interests: ["product design", "stand-up comedy", "bouldering", "Tamil cinema", "journalling"],
      pets: [],
      dealbreakers: ["cruelty", "refusing to grow"],
      partnerAgeMin: 24,
      partnerAgeMax: 32,
      attachment: "Fearful-Avoidant",
      attachmentScore: 48,
      readinessScore: 60,
      growthAreas: ["staying when his anxiety says run", "being seen without performing"],
      strengths: ["insight", "humour", "deep thinking"],
      coreValues: ["growth", "authenticity", "meaning", "connection"],
      summary:
        "Dev moved from Chennai to Pune to outrun a version of himself he didn't like. He's done a lot of work since — therapy, journalling, the whole thing. He wants something real but still braces for it to fall apart. He's tired of being the one who sabotages good things.",
      coachingFocus: "Staying in the room when things get vulnerable instead of cracking a joke.",
      photos: [],
      prompts: [
        { question: "The thing about me is", answer: "I'll make you laugh and then say something devastatingly honest. That's kind of my move." },
        { question: "I'm in therapy because", answer: "I ran from something good and I don't want to do it again." },
        { question: "A perfect evening", answer: "Bouldering, bad movie, good conversation about why the movie was bad." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I deflect with humour. I know it. I'm working on it.",
      familyExpectations: "Love my family. Lots of opinions about my choices. Learning to hold both.",
      lifeArchitecture: "Pune is growing on me. Open to Bangalore. Not Chennai, not yet.",
      offers: ["will make you laugh every day", "someone who thinks about relationship dynamics seriously", "no games"],
      needs: ["patience with regression", "verbal affirmation", "someone who doesn't give up easily"],
    },
  },

  // ── 13 Meera Joshi · Pune · F · 25 · Secure · Marriage ──────────────────
  {
    userId: seedId(13),
    email: "meera.joshi@seed.biggdate.app",
    username: "meera_joshi",
    fullName: "Meera Joshi",
    profile: {
      name: "Meera Joshi",
      age: 25,
      birthday: "2000-12-25",
      zodiac: "Capricorn",
      city: "Pune",
      gender: "Woman",
      orientation: "Straight",
      pronouns: "she/her",
      hometown: "Nashik",
      jobTitle: "Therapist",
      company: "iCall (TISS)",
      education: "TISS Mumbai",
      height: "5'5\"",
      religion: "Hindu",
      politics: "Progressive",
      ethnicity: "Indian",
      partnerGender: "Man",
      intent: "marriage",
      relationshipStyle: "Monogamous",
      hasKids: false,
      wantsKids: "yes",
      loveLanguage: "Quality Time",
      drinking: "never",
      smoking: "never",
      exercise: "often",
      languages: ["Marathi", "Hindi", "English"],
      interests: ["narrative therapy", "Sufi music", "hiking the Sahyadris", "reading Arundhati Roy", "plants"],
      pets: ["cat", "plants (counts)"],
      dealbreakers: ["contempt", "no self-reflection"],
      partnerAgeMin: 25,
      partnerAgeMax: 35,
      attachment: "Secure",
      attachmentScore: 88,
      readinessScore: 85,
      growthAreas: ["receiving without deflecting", "trusting her own pace"],
      strengths: ["holding space", "emotional intelligence", "warmth that doesn't require anything in return"],
      coreValues: ["healing", "presence", "simplicity", "love"],
      summary:
        "Meera is a therapist who is, ironically, very easy to be with. She doesn't analyse people she dates — she's off the clock. She's 25 and knows she wants a lifelong partner; she's been clear about that her whole life. She's not in a rush, but she's not playing either.",
      coachingFocus: "Letting a partner love her the way she loves others.",
      photos: [],
      prompts: [
        { question: "Before you ask, no", answer: "I won't therapise you. I'm off the clock." },
        { question: "My Saturdays look like", answer: "Sahyadri trail, rajma rice, Nusrat Fateh Ali Khan, lights out by 10." },
        { question: "I fall for people who", answer: "Are trying, even when it's hard." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "Calm, direct, and I always come back to repair. Repair is non-negotiable for me.",
      familyExpectations: "Close family in Nashik. I want to build something like what they have.",
      lifeArchitecture: "Pune is home. Maybe a small house with a big garden someday.",
      offers: ["emotional safety", "a relationship that heals rather than harms", "someone in your corner unconditionally"],
      needs: ["effort", "presence over grand gestures", "someone who wants the ordinary life as much as the beautiful one"],
    },
  },

  // ── 14 Nisha Pillai · Pune · F · 32 · Anxious · Casual ──────────────────
  {
    userId: seedId(14),
    email: "nisha.pillai@seed.biggdate.app",
    username: "nisha_pillai",
    fullName: "Nisha Pillai",
    profile: {
      name: "Nisha Pillai",
      age: 32,
      birthday: "1993-08-16",
      zodiac: "Leo",
      city: "Pune",
      gender: "Woman",
      orientation: "Bisexual",
      pronouns: "she/her",
      hometown: "Thiruvananthapuram",
      jobTitle: "Senior UX Researcher",
      company: "Persistent Systems",
      education: "MIT Institute of Design",
      height: "5'7\"",
      religion: "Agnostic",
      politics: "Progressive",
      ethnicity: "Indian",
      partnerGender: "Any",
      intent: "casual",
      relationshipStyle: "Figuring it out after a long relationship",
      hasKids: false,
      wantsKids: "open",
      loveLanguage: "Physical Touch",
      drinking: "social",
      smoking: "never",
      exercise: "often",
      languages: ["Malayalam", "English", "Hindi", "Marathi"],
      interests: ["user research", "salsa dancing", "Kerala literature", "distance running", "coffee rituals"],
      pets: [],
      dealbreakers: ["homophobia", "emotional manipulation"],
      partnerAgeMin: 26,
      partnerAgeMax: 40,
      attachment: "Anxious",
      attachmentScore: 50,
      readinessScore: 48,
      growthAreas: ["rebuilding identity post-breakup", "not jumping into intensity to feel alive"],
      strengths: ["empathy", "deep listening", "pattern recognition in people"],
      coreValues: ["authenticity", "freedom", "connection", "joy"],
      summary:
        "Nisha just came out of a 5-year relationship and is rebuilding herself from scratch — which is terrifying and quietly exciting. She's here to meet people, feel something real, and figure out what she actually wants now that she's not defined by 'we'.",
      coachingFocus: "Distinguishing what she wants from what she's running from.",
      photos: [],
      prompts: [
        { question: "Right now I need", answer: "Good conversation, no pressure, someone who finds Pune underrated." },
        { question: "I'm the person at the party who", answer: "Ends up in deep conversation with your most interesting friend in the kitchen." },
        { question: "I just got out of", answer: "A long relationship. I'm not broken, I'm just recalibrating." },
      ],
      profileVisibility: "visible",
      showAge: true,
      showCity: true,
      showWork: true,
      showEducation: true,
      conflictStyle: "I over-explain when I'm anxious. I've been told I apologise too much.",
      familyExpectations: "Complicated. Kerala family, conservative values, queer identity. It's a whole thing.",
      lifeArchitecture: "Pune for now. Would love to slow-travel for a year if I could swing it.",
      offers: ["real conversation", "someone who makes you feel genuinely understood", "spontaneity"],
      needs: ["no pressure on timelines", "patience during recalibration", "someone secure enough to not need certainty from me yet"],
    },
  },
];

async function reset() {
  const ids = PERSONAS.map((p) => p.userId);
  await sql`DELETE FROM profiles WHERE user_id = ANY(${ids}::uuid[])`;
  await sql`DELETE FROM account_handles WHERE user_id = ANY(${ids}::uuid[])`;
  console.log("Cleared existing seed rows.");
}

async function main() {
  const shouldReset = process.argv.includes("--reset");
  if (shouldReset) await reset();

  let ok = 0;
  for (const p of PERSONAS) {
    await upsertAccountHandle({
      userId: p.userId,
      email: p.email,
      username: p.username,
      fullName: p.fullName,
    });
    await upsertProfile(p.userId, p.profile);
    console.log(`✓  ${p.profile.name.padEnd(20)} ${p.profile.city.padEnd(14)} ${p.profile.attachment.padEnd(18)} ${p.profile.intent}`);
    ok++;
  }

  console.log(`\nSeeded ${ok}/${PERSONAS.length} profiles.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
