-- Fix type mismatch between intros.id and soul_knock_responses.intro_id.
--
-- Root cause: intros.id was always TEXT, with values in the format
-- "intro_<uuid>" (generated by createId("intro") in repo.ts).
-- The original migration attempted ALTER COLUMN id TYPE uuid, which fails
-- because the "intro_" prefix makes existing values invalid uuids.
--
-- Changing intros.id to uuid would silently break every query in repo.ts
-- that passes the full "intro_..." string. The correct fix is the inverse:
-- change soul_knock_responses.intro_id from uuid → text so it matches what
-- the application actually stores. This also unblocks inserts that were
-- previously rejected by Postgres with "invalid input syntax for type uuid".

BEGIN;

-- Change soul_knock_responses.intro_id from uuid → text to match intros.id
ALTER TABLE soul_knock_responses
  ALTER COLUMN intro_id TYPE text USING intro_id::text;

-- Now both columns are text — add the FK for referential integrity
ALTER TABLE soul_knock_responses
  ADD CONSTRAINT fk_soul_knock_responses_intro_id
  FOREIGN KEY (intro_id) REFERENCES intros(id) ON DELETE CASCADE;

COMMIT;
