alter table profiles add column if not exists pronouns text;
alter table profiles add column if not exists hometown text;
alter table profiles add column if not exists job_title text;
alter table profiles add column if not exists company text;
alter table profiles add column if not exists education text;
alter table profiles add column if not exists height text;
alter table profiles add column if not exists religion text;
alter table profiles add column if not exists politics text;
alter table profiles add column if not exists ethnicity text;
alter table profiles add column if not exists relationship_style text;
alter table profiles add column if not exists languages text default '[]';
alter table profiles add column if not exists interests text default '[]';
alter table profiles add column if not exists pets text default '[]';
alter table profiles add column if not exists prompts text default '[]';
alter table profiles add column if not exists profile_visibility text default 'visible';
alter table profiles add column if not exists show_age boolean default true;
alter table profiles add column if not exists show_city boolean default true;
alter table profiles add column if not exists show_work boolean default true;
alter table profiles add column if not exists show_education boolean default true;
